import test from 'node:test';
import assert from 'node:assert/strict';
import {createMarketingTrace} from '../lib/marketing_trace.js';
import {buildMarketingSupport} from '../lib/marketing_sales_support.js';
const sender='ricardo.boltechgroup@gmail.com',buyer='buyer@example.test';
function fixture(){let row={eventId:'marketing-fixture',from:'RSI-01',opportunityId:'rec0123456789abcd',createdAt:'2026-10-07T19:00:00Z',material:buildMarketingSupport({rsi:'RSI-01',accounts:[]})};
 const messages={sent:{id:'sent',from:sender,to:buyer,sent:true,threadId:'thread',text:row.material.materials.es.text,receivedAt:'2026-10-07T19:10:00Z'},reply:{id:'reply',from:buyer,to:sender,sent:false,threadId:'thread',text:'Quiero revisar ese procedimiento',receivedAt:'2026-10-07T19:20:00Z'}};
 const worker=createMarketingTrace({readEvent:async()=>structuredClone(row),updateEvent:async(old,next)=>{assert.deepEqual(old,row);row=next;},listEvents:async()=>[row],search:async()=>messages.sent?[{id:'sent'}]:[],thread:async()=>messages.reply?[messages.reply]:[],message:async id=>messages[id],lead:async id=>({id,fields:{'Contact Email':buyer}}),sender,now:()=> '2026-10-07T19:30:00Z'});
 return {worker,messages,row:()=>row,review:()=>worker.review({eventId:row.eventId,from:row.from,materialFingerprint:row.material.fingerprint}),input:{eventId:row.eventId,from:row.from}};
}
test('request acceptance use and actual reply are separate durable stages and never count a sale',async()=>{const f=fixture();assert.equal((await f.worker.metrics()).pendingAcceptance,1);await f.review();assert.equal((await f.worker.metrics()).used,0);await f.worker.use({...f.input,messageId:'sent',language:'es'});assert.equal((await f.worker.metrics()).resultsVerified,0);await f.worker.result({...f.input,messageId:'reply'});const s=await f.worker.metrics();assert.deepEqual([s.requested,s.accepted,s.used,s.resultsVerified],[1,1,1,1]);assert.equal(s.saleInferred,false);assert.equal((await f.worker.use({...f.input,messageId:'sent',language:'es'})).reused,true);});
test('actor version usage and result gates reject invented adoption',async()=>{const f=fixture();await assert.rejects(f.worker.review({...f.input,from:'RSI-02'}),/OWNER_MISMATCH/);await assert.rejects(f.worker.review({...f.input,materialFingerprint:'fake'}),/VERSION_MISMATCH/);await assert.rejects(f.worker.use({...f.input,messageId:'sent',language:'es'}),/ACCEPTANCE_REQUIRED/);await f.review();f.messages.sent.text='Otro mensaje';await assert.rejects(f.worker.use({...f.input,messageId:'sent',language:'es'}),/USAGE_UNVERIFIED/);assert.equal((await f.worker.metrics()).used,0);await assert.rejects(f.worker.result({...f.input,messageId:'reply'}),/USAGE_REQUIRED/);});
test('wrong account automatic reply old message or different thread is not a commercial result',async()=>{const f=fixture();await f.review();await f.worker.use({...f.input,messageId:'sent',language:'es'});for(const change of [{from:'wrong@example.test'},{automatic:true},{threadId:'other'},{receivedAt:'2026-10-07T18:00:00Z'}]){const old={...f.messages.reply};Object.assign(f.messages.reply,change);await assert.rejects(f.worker.result({...f.input,messageId:'reply'}),/RESULT_UNVERIFIED/);f.messages.reply=old;}assert.equal((await f.worker.metrics()).resultsVerified,0);});
test('existing Gmail history automatically connects verified use and customer reply',async()=>{const f=fixture();await f.review();const r=await f.worker.reconcile(f.input);assert.equal(r.used,true);assert.equal(r.resultVerified,true);assert.equal(r.sendingPerformed,false);assert.equal(r.saleInferred,false);assert.equal((await f.worker.reconcile(f.input)).status,'CUSTOMER_REPLY_VERIFIED');});
test('no matching sent material remains pending with a durable real check',async()=>{const f=fixture();await f.review();f.messages.sent.text='Unrelated correspondence';const r=await f.worker.reconcile(f.input);assert.equal(r.status,'NO_VERIFIED_USE');assert.equal(r.used,false);assert.equal(f.row().marketingHistoryCheck.candidateMessages,1);});
