import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const router=(await readFile('lib/sales_marketing_router.js','utf8')).replace('export function','function');
const support=(await readFile('lib/marketing_sales_support.js','utf8')).replace(/^import .*\n/gm,'').replace(/export /g,'').replace(/crypto\.createHash\('sha256'\)\.update\(JSON.stringify\(support\)\)\.digest\('hex'\)/g,"'n8n-private-support'");
const pilot=JSON.parse(await readFile('config/commercial_pilot.json','utf8'));
const decisionCode=`${router}\nconst event=$json.body||$json;const decision=routeSalesMarketingEvent(event);return [{json:decision}];`;
const materialCode=`const pilot=${JSON.stringify(pilot)};\n${support}\nconst decision=$json; if(!decision.success)return [{json:decision}]; const material=buildMarketingSupport({rsi:decision.from,accounts:[{sourceRecordId:decision.opportunityId,account:'CRM-linked opportunity',route:'REVIEW_COHORT_ELIGIBILITY',gates:['SALES_REVIEW','LIVE_HISTORY_REQUIRED']}]});return [{json:{...decision,material,deliveredTo:decision.returnTo,usedBySales:false}}];`;
const nodes=[
  {id:'receive',name:'Recibir solicitud del RSI',type:'n8n-nodes-base.webhook',typeVersion:2,position:[0,0],webhookId:'boltech-sales-marketing',parameters:{httpMethod:'POST',path:'boltech-sales-marketing',authentication:'headerAuth',responseMode:'responseNode',options:{}},credentials:{httpHeaderAuth:{id:'boltechInteragentHeader',name:'Boltech interagent local'}}},
  {id:'decide',name:'Directora asigna ruta y alternativa',type:'n8n-nodes-base.code',typeVersion:2,position:[260,0],parameters:{jsCode:decisionCode}},
  {id:'branch',name:'Apoyo o decisión de Dirección',type:'n8n-nodes-base.if',typeVersion:2.2,position:[520,0],parameters:{conditions:{options:{caseSensitive:true,leftValue:'',typeValidation:'strict',version:2},conditions:[{id:'target',leftValue:'={{ $json.to }}',rightValue:'marketing-director',operator:{type:'string',operation:'equals'}}],combinator:'and'},options:{}}},
  {id:'marketing',name:'Mercadeo entrega apoyo al RSI solicitante',type:'n8n-nodes-base.code',typeVersion:2,position:[800,-140],parameters:{jsCode:materialCode}},
  {id:'director',name:'Dirección recibe cierre o bloqueo',type:'n8n-nodes-base.code',typeVersion:2,position:[800,160],parameters:{jsCode:"return [{json:{...$json,directorActionPending:$json.success===true,notificationDelivered:false, instruction:'RSI-03 informa a Directora; Directora verifica y comunica a Ricardo. Conservar esta ejecución como evidencia; no contabilizar cobro por el aviso.'}}];"}},
  {id:'response',name:'Devolver resultado y conservar ejecución',type:'n8n-nodes-base.respondToWebhook',typeVersion:1.4,position:[1080,0],parameters:{respondWith:'json',responseBody:'={{ $json }}',options:{responseCode:'={{ $json.success ? 200 : 400 }}'}}}
];
const link=name=>({node:name,type:'main',index:0});
const workflow={id:'boltechSalesMarketing',name:'Boltech | Ventas ↔ Mercadeo | apoyo y cierre',active:false,nodes,connections:{'Recibir solicitud del RSI':{main:[[link('Directora asigna ruta y alternativa')]]},'Directora asigna ruta y alternativa':{main:[[link('Apoyo o decisión de Dirección')]]},'Apoyo o decisión de Dirección':{main:[[link('Mercadeo entrega apoyo al RSI solicitante')],[link('Dirección recibe cierre o bloqueo')]]},'Mercadeo entrega apoyo al RSI solicitante':{main:[[link('Devolver resultado y conservar ejecución')]]},'Dirección recibe cierre o bloqueo':{main:[[link('Devolver resultado y conservar ejecución')]]}},settings:{executionOrder:'v1',timezone:'America/El_Salvador',saveDataSuccessExecution:'all',saveDataErrorExecution:'all',executionTimeout:60},pinData:{},meta:{templateCredsSetupCompleted:false},tags:[]};
await mkdir('config/n8n',{recursive:true});await writeFile('config/n8n/boltech_sales_marketing.json',JSON.stringify(workflow,null,2)+'\n');
console.log(JSON.stringify({workflow:workflow.id,nodes:nodes.length,sha256:createHash('sha256').update(JSON.stringify(workflow)).digest('hex'),secretsIncluded:false,published:false}));
